spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://postgres:5432/database
    username: db_user
    password: S3cret
management:
  endpoints:
    web:
      exposure:
        include: [ "prometheus" ]
---
spring:
  config:
    activate:
      on-profile: default
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
management:
  endpoints:
    web:
      exposure:
        include: '*'

#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#
#management.metrics.enable.http.server.requests=true
#management.endpoints.web.exposure.include=*